# Book settings

title: Experimentation 1
author: Jeshua Tromp & Henk van Steenbergen
copyright: "Leiden University; Attribution: Jeshua Tromp & Henk van Steenbergen, Leiden University, with CC BY-NC-SA 2.0 license"  # Copyright year to be placed in the footer
logo: logo.png

# Execution settings
execute:
  execute_notebooks         : "off" # Whether to execute notebooks at build time. Must be one of ("auto", "force", "cache", "off")
  cache                     : ""    # A path to the jupyter cache that will be used to store execution artifacts. Defaults to `_build/.jupyter_cache/`
  exclude_patterns          : []    # A list of patterns to *skip* in execution (e.g. a notebook that takes a really long time)
  timeout                   : 360    # The maximum time (in seconds) each notebook cell is allowed to run.
  run_in_temp               : false # If `True`, then a temporary directory will be created and used as the command working directory (cwd),
  # otherwise the notebook's parent directory will be the cwd.
  allow_errors              : true # If `False`, when a code cell raises an error the execution is stopped, otherwise all cells are always run.
  stderr_output             : show  # One of 'show', 'remove', 'remove-warn', 'warn', 'error', 'severe'

bibtex_bibfiles:
  - references.bib

parse:
  myst_enable_extensions:
    - colon_fence
    - amsmath
    - dollarmath
    - linkify
    - substitution
    - tasklist
    - html_image

# Online stuff
repository:
  url                       : https://github.com/JeshuaT/Experimentation1  # The URL to your book's repository
#  path_to_book              : ""  # A path to your book's folder, relative to the repository root.
  branch                    : main  # Which branch of the repository should be used when creating links

launch_buttons:
  notebook_interface        : classic
  binderhub_url             : https://mybinder.org
  colab_url                 : "https://colab.research.google.com"

html:
  use_repository_button: true
  use_issues_button: true
  use_edit_page_button: true
